package: d2u_history
version: '1.0.2'
author: Tobias Krais

page:
    title: 'translate:d2u_history'
    perm: 'd2u_history[]'
    icon: rex-icon fa-history
    subpages:
        history: { title: 'translate:d2u_history_events', icon: rex-icon fa-history }
        setup: { title: 'translate:d2u_helper_setup', icon: rex-icon rex-icon-install, itemClass: pull-right, perm: 'd2u_history[settings]' }
        settings: { title: 'translate:d2u_helper_settings', icon: rex-icon rex-icon-system, itemClass: pull-right, perm: 'd2u_history[settings]' }

requires:
    packages:
        d2u_helper: '>=1.14.0'
    php: '>=8.0'
        
installer_ignore:
    - .github